runtime: python38
instance_class: F1

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
  STATIC_ROOT: "static"
  DEBUG: "0"

inbound_services:
  - warmup

entrypoint: gunicorn -b :$PORT tripman.wsgi
