runtime: python39
instance_class: F1
automatic_scaling:
  min_instances: 1

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static/

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto

env_variables:
  STATIC_ROOT: "static"
  DEBUG: "0"
  DEPLOYED: "1"
  # substituted during build in GitHub actions
  BRANCH_NAME: ${BRANCH_NAME}
  DJANGO_ADMIN_NAME: ${DJANGO_ADMIN_NAME}
  DJANGO_ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL}
  DJANGO_ADMIN_PASSWORD: ${DJANGO_ADMIN_PASSWORD}

inbound_services:
  - warmup

readiness_check:
  path: "/healthcheck"

entrypoint: python manage.py migrate && gunicorn -b :$PORT tripman.wsgi
