# Generated by Django 3.0.5 on 2020-04-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Дополнительный сервис', 'verbose_name_plural': 'Дополнительные сервисы'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Путешествие', 'verbose_name_plural': 'Путешествия'},
        ),
        migrations.AlterModelOptions(
            name='tripdefinition',
            options={'verbose_name': 'Путевка', 'verbose_name_plural': 'Путевки'},
        ),
    ]
