# Generated by Django 3.0.5 on 2020-04-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20200411_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.IntegerField(verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='tripdefinition',
            name='price',
            field=models.IntegerField(verbose_name='Цена (руб)'),
        ),
    ]
