# Generated by Django 3.0.5 on 2020-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_auto_20200412_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdefinition',
            name='location',
            field=models.CharField(default='', max_length=50,
                                   verbose_name='Населенный пункт'),
            preserve_default=False,
        ),
    ]
