# Generated by Django 3.0.5 on 2020-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_tripdefinition_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка (%)'),
        ),
    ]
