# Generated by Django 3.0.5 on 2020-04-18 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_auto_20200412_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент',
                     'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'дополнительный сервис',
                     'verbose_name_plural': 'дополнительные сервисы'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'путешествие',
                     'verbose_name_plural': 'путешествия'},
        ),
        migrations.AlterModelOptions(
            name='tripdefinition',
            options={'verbose_name': 'путевка',
                     'verbose_name_plural': 'путевки'},
        ),
        migrations.RenameField(
            model_name='tripdefinition',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tripdefinition',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
