# Generated by Django 3.0.5 on 2020-04-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_auto_20200418_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdefinition',
            name='services',
            field=models.ManyToManyField(blank=True, to='main.Service',
                                         verbose_name='Сервисы'),
        ),
    ]
