# Generated by Django 3.0.5 on 2020-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_auto_20200418_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdefinition',
            name='end_date',
            field=models.DateField(verbose_name='Дата возвращения'),
        ),
        migrations.AlterField(
            model_name='tripdefinition',
            name='start_date',
            field=models.DateField(verbose_name='Дата отправления'),
        ),
    ]
