# Generated by Django 3.2 on 2021-04-16 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_excursion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdefinition',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='auth.user', verbose_name='Создатель'),
            preserve_default=False,
        ),
    ]
