# Generated by Django 3.2 on 2021-04-16 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0012_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdefinition',
            name='location',
        ),
    ]
