# Generated by Django 3.2 on 2021-04-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0014_client_total_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='sell_date',
            field=models.DateField(blank=True, verbose_name='Дата продажи'),
        ),
    ]
