# Generated by Django 3.2 on 2021-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0016_excursion_times_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='times_visited',
            field=models.IntegerField(default=0,
                                      verbose_name='Посещений экскурсии'),
        ),
    ]
