name: 'Close pull request'
on:
  pull_request:
    types: [ closed ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  destroy-preview-app:
    name: 'Destroy preview app'
    runs-on: ubuntu-22.04
    steps:
      - name: Destroy the preview app
        uses: dokku/github-action@66fb7d4443732f94005366c22c562e5ddcbb1d4b
        with:
          command: review-apps:destroy
          git_remote_url: 'ssh://dokku@164.92.191.5:22/tripman'
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          review_app_name: tripman-pr-${{ github.event.pull_request.number }}
