name: 'Close pull request'
on:
  pull_request:
    types: [ closed ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  destroy-preview-app:
    name: 'Destroy preview app'
    runs-on: ubuntu-22.04
    steps:
      - name: Destroy preview app
        uses: dokku/github-action@66fb7d4443732f94005366c22c562e5ddcbb1d4b
        with:
          command: review-apps:destroy
          git_remote_url: 'ssh://dokku@164.92.191.5:22/tripman'
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          review_app_name: tripman-pr-${{ github.event.pull_request.number }}

  destroy-mysql-instance:
    name: Destroy mysql instance
    runs-on: ubuntu-22.04
    needs: [ destroy-preview-app ] # otherwise cannot unlink from running app
    steps:
      - name: Destroy mysql instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 164.92.191.5
          username: dokku
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: true
          script: mysql:destroy tripman-pr-${{ github.event.pull_request.number }}-sql --force
