name: Main workflow
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  #  Of course these env variables are used only on GitHub Actions
  #  prod env variables are stored in another place
  SECRET_KEY: "398jy60_15v)f-b=rdg@hryajjfxo6hl*c0ll1+bg7ay-gjr)l"
  DATABASE_URL: "mysql://root:root@127.0.0.1:8888/enfight?charset=utf8mb4"
  DEBUG: "1"
  DJANGO_ADMIN_NAME: "user"
  DJANGO_ADMIN_EMAIL: "user@example.com"
  DJANGO_ADMIN_PASSWORD: "root"
  STATIC_ROOT: "static"
jobs:
  deploy-prod:
    name: 'Deploy prod'
    runs-on: ubuntu-22.04
    if: github.ref_name == 'master'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy prod
        uses: dokku/github-action@66fb7d4443732f94005366c22c562e5ddcbb1d4b
        with:
          git_remote_url: 'ssh://dokku@164.92.191.5:22/tripman'
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          git_push_flags: --force
